package com.fitnessapp.summary.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One calendar day of aggregated activity, as read out of Health Connect.
 *
 * [dateEpochDay] ([java.time.LocalDate.toEpochDay]) is the primary key rather than
 * an autogenerated row id: unlike a habit, a day *has* a natural unique key, so
 * using it directly makes every write an idempotent upsert and gives Firestore a
 * stable document id for free - no separate syncId UUID needed (that pattern only
 * exists in the sibling habits app because habit rows have no natural key).
 *
 * Every numeric field uses 0 for "no data", never null. Health Connect legitimately
 * has nothing for most of these on a day the watch wasn't worn, and 0-vs-null would
 * otherwise leak Kotlin nullability into every chart and formatter. The rule is
 * applied consistently: readers must treat 0 as "unknown", which is why averages
 * across a week deliberately skip zero days rather than dragging the mean down -
 * see [SummaryRepository.computeWeekSummary].
 */
@Entity(tableName = "daily_summaries")
data class DailySummary(
    @PrimaryKey val dateEpochDay: Long,

    // Movement
    val steps: Long = 0,
    val activeCaloriesKcal: Int = 0,
    val totalCaloriesKcal: Int = 0,
    val distanceMeters: Int = 0,

    // Heart
    val restingHeartRate: Int = 0,
    val avgHeartRate: Int = 0,
    val minHeartRate: Int = 0,
    val maxHeartRate: Int = 0,

    // Sleep - attributed to the day the user WOKE UP on, which is how Garmin
    // itself reports a night (a session running 23:40 Mon -> 07:10 Tue is Tuesday's
    // sleep). See HealthConnectReader.readSleepFor.
    val sleepTotalMinutes: Int = 0,
    val sleepDeepMinutes: Int = 0,
    val sleepLightMinutes: Int = 0,
    val sleepRemMinutes: Int = 0,
    val sleepAwakeMinutes: Int = 0,

    // Rolled up from the day's workouts (kept denormalised so the week screen can
    // aggregate without joining the workouts table for every day it renders)
    val workoutCount: Int = 0,
    val workoutMinutes: Int = 0,

    val updatedAtMillis: Long = System.currentTimeMillis()
) {
    /** True when Health Connect had nothing at all for this date - see [SummaryRepository.upsertDay]. */
    val isEmpty: Boolean
        get() = steps == 0L && activeCaloriesKcal == 0 && totalCaloriesKcal == 0 &&
            distanceMeters == 0 && restingHeartRate == 0 && avgHeartRate == 0 &&
            sleepTotalMinutes == 0 && workoutCount == 0

    val hasSleep: Boolean get() = sleepTotalMinutes > 0
    val hasMovement: Boolean get() = steps > 0 || distanceMeters > 0 || activeCaloriesKcal > 0
}
